version: "3"

services:
  redis:
    image: redis
    container_name: redis-driverservice
    restart: always
    ports:
      - 6379:6379
  driverservice:
    image: omvk97/bachelordriverservice
    container_name: driverservice
    environment:
      EXPRESS_PORT: 5001
      SOCKETIO_PORT: 5002
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 5001:5001
      - 5002:5002
    depends_on:
      - redis
  performance_monitoring:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus-data:/prometheus-data"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    