version: "3"

services:
  driverservice0:
    image: omvk97/driverservice
    container_name: driverservice0
    env_file:
      - .env
    ports:
      - 5001:5001
      - 5002:5002
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  
  driverservice1:
    image: omvk97/driverservice
    container_name: driverservice1
    env_file:
      - .env
    ports:
      - 5003:5001
      - 5004:5002
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  driverservice2:
    image: omvk97/driverservice
    container_name: driverservice2
    env_file:
      - .env
    ports:
      - 5005:5001
      - 5006:5002
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  
  # performance_monitoring:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
